global:
  scrape_interval: 5s 
  external_labels:
    monitor: 'docker-monitoring-stack'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
