name: Docker Build and K8s Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        run: sudo docker build -t myimage .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: sudo docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/myimage:latest

      - name: Push Docker image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/myimage:latest

      - name: Deploy to kubernetes
        run: sudo kubectl apply -f Deployment.yaml

      - name: Restart deployment
        run: sudo kubectl rollout restart deployment myapp || true

      - name: Expose to browser
        run: sudo kubectl apply -f Service.yaml
